/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppSystemAnalyticsRouteImport } from './routes/app.system-analytics'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppMyResultsRouteImport } from './routes/app.my-results'
import { Route as AppMyAssessmentsRouteImport } from './routes/app.my-assessments'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiReviewRouteImport } from './routes/app.ai-review'
import { Route as AppAiModelsRouteImport } from './routes/app.ai-models'
import { Route as AppAiInsightsRouteImport } from './routes/app.ai-insights'
import { Route as AppTrainingsIndexRouteImport } from './routes/app.trainings.index'
import { Route as AppQuestionsIndexRouteImport } from './routes/app.questions.index'
import { Route as AppParticipantsIndexRouteImport } from './routes/app.participants.index'
import { Route as AppAssessmentsIndexRouteImport } from './routes/app.assessments.index'
import { Route as AssessmentIdSolveRouteImport } from './routes/assessment.$id.solve'
import { Route as AssessmentIdResultRouteImport } from './routes/assessment.$id.result'
import { Route as AssessmentIdAccessRouteImport } from './routes/assessment.$id.access'
import { Route as AppTrainingsIdRouteImport } from './routes/app.trainings.$id'
import { Route as AppQuestionsEquivalentGroupsRouteImport } from './routes/app.questions.equivalent-groups'
import { Route as AppQuestionsIdRouteImport } from './routes/app.questions.$id'
import { Route as AppParticipantsUserIdRouteImport } from './routes/app.participants.$userId'
import { Route as AppAssessmentsNewRouteImport } from './routes/app.assessments.new'
import { Route as AppAssessmentsIdRouteImport } from './routes/app.assessments.$id'
import { Route as AppAssessmentsIdResultsRouteImport } from './routes/app.assessments.$id.results'
import { Route as AppAssessmentsIdPostTestRouteImport } from './routes/app.assessments.$id.post-test'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemAnalyticsRoute = AppSystemAnalyticsRouteImport.update({
  id: '/system-analytics',
  path: '/system-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppMyResultsRoute = AppMyResultsRouteImport.update({
  id: '/my-results',
  path: '/my-results',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAssessmentsRoute = AppMyAssessmentsRouteImport.update({
  id: '/my-assessments',
  path: '/my-assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiReviewRoute = AppAiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => AppRoute,
} as any)
const AppAiModelsRoute = AppAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingsIndexRoute = AppTrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsIndexRoute = AppQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsIndexRoute = AppParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsIndexRoute = AppAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => AppRoute,
} as any)
const AssessmentIdSolveRoute = AssessmentIdSolveRouteImport.update({
  id: '/assessment/$id/solve',
  path: '/assessment/$id/solve',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdResultRoute = AssessmentIdResultRouteImport.update({
  id: '/assessment/$id/result',
  path: '/assessment/$id/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdAccessRoute = AssessmentIdAccessRouteImport.update({
  id: '/assessment/$id/access',
  path: '/assessment/$id/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingsIdRoute = AppTrainingsIdRouteImport.update({
  id: '/trainings/$id',
  path: '/trainings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsEquivalentGroupsRoute =
  AppQuestionsEquivalentGroupsRouteImport.update({
    id: '/questions/equivalent-groups',
    path: '/questions/equivalent-groups',
    getParentRoute: () => AppRoute,
  } as any)
const AppQuestionsIdRoute = AppQuestionsIdRouteImport.update({
  id: '/questions/$id',
  path: '/questions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsUserIdRoute = AppParticipantsUserIdRouteImport.update({
  id: '/participants/$userId',
  path: '/participants/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsNewRoute = AppAssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsIdRoute = AppAssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsIdResultsRoute = AppAssessmentsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppAssessmentsIdRoute,
} as any)
const AppAssessmentsIdPostTestRoute =
  AppAssessmentsIdPostTestRouteImport.update({
    id: '/post-test',
    path: '/post-test',
    getParentRoute: () => AppAssessmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/ai-models': typeof AppAiModelsRoute
  '/app/ai-review': typeof AppAiReviewRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/my-assessments': typeof AppMyAssessmentsRoute
  '/app/my-results': typeof AppMyResultsRoute
  '/app/results': typeof AppResultsRoute
  '/app/system-analytics': typeof AppSystemAnalyticsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/assessments/$id': typeof AppAssessmentsIdRouteWithChildren
  '/app/assessments/new': typeof AppAssessmentsNewRoute
  '/app/participants/$userId': typeof AppParticipantsUserIdRoute
  '/app/questions/$id': typeof AppQuestionsIdRoute
  '/app/questions/equivalent-groups': typeof AppQuestionsEquivalentGroupsRoute
  '/app/trainings/$id': typeof AppTrainingsIdRoute
  '/assessment/$id/access': typeof AssessmentIdAccessRoute
  '/assessment/$id/result': typeof AssessmentIdResultRoute
  '/assessment/$id/solve': typeof AssessmentIdSolveRoute
  '/app/assessments/': typeof AppAssessmentsIndexRoute
  '/app/participants/': typeof AppParticipantsIndexRoute
  '/app/questions/': typeof AppQuestionsIndexRoute
  '/app/trainings/': typeof AppTrainingsIndexRoute
  '/app/assessments/$id/post-test': typeof AppAssessmentsIdPostTestRoute
  '/app/assessments/$id/results': typeof AppAssessmentsIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/ai-models': typeof AppAiModelsRoute
  '/app/ai-review': typeof AppAiReviewRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/my-assessments': typeof AppMyAssessmentsRoute
  '/app/my-results': typeof AppMyResultsRoute
  '/app/results': typeof AppResultsRoute
  '/app/system-analytics': typeof AppSystemAnalyticsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/assessments/$id': typeof AppAssessmentsIdRouteWithChildren
  '/app/assessments/new': typeof AppAssessmentsNewRoute
  '/app/participants/$userId': typeof AppParticipantsUserIdRoute
  '/app/questions/$id': typeof AppQuestionsIdRoute
  '/app/questions/equivalent-groups': typeof AppQuestionsEquivalentGroupsRoute
  '/app/trainings/$id': typeof AppTrainingsIdRoute
  '/assessment/$id/access': typeof AssessmentIdAccessRoute
  '/assessment/$id/result': typeof AssessmentIdResultRoute
  '/assessment/$id/solve': typeof AssessmentIdSolveRoute
  '/app/assessments': typeof AppAssessmentsIndexRoute
  '/app/participants': typeof AppParticipantsIndexRoute
  '/app/questions': typeof AppQuestionsIndexRoute
  '/app/trainings': typeof AppTrainingsIndexRoute
  '/app/assessments/$id/post-test': typeof AppAssessmentsIdPostTestRoute
  '/app/assessments/$id/results': typeof AppAssessmentsIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/ai-models': typeof AppAiModelsRoute
  '/app/ai-review': typeof AppAiReviewRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/my-assessments': typeof AppMyAssessmentsRoute
  '/app/my-results': typeof AppMyResultsRoute
  '/app/results': typeof AppResultsRoute
  '/app/system-analytics': typeof AppSystemAnalyticsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/assessments/$id': typeof AppAssessmentsIdRouteWithChildren
  '/app/assessments/new': typeof AppAssessmentsNewRoute
  '/app/participants/$userId': typeof AppParticipantsUserIdRoute
  '/app/questions/$id': typeof AppQuestionsIdRoute
  '/app/questions/equivalent-groups': typeof AppQuestionsEquivalentGroupsRoute
  '/app/trainings/$id': typeof AppTrainingsIdRoute
  '/assessment/$id/access': typeof AssessmentIdAccessRoute
  '/assessment/$id/result': typeof AssessmentIdResultRoute
  '/assessment/$id/solve': typeof AssessmentIdSolveRoute
  '/app/assessments/': typeof AppAssessmentsIndexRoute
  '/app/participants/': typeof AppParticipantsIndexRoute
  '/app/questions/': typeof AppQuestionsIndexRoute
  '/app/trainings/': typeof AppTrainingsIndexRoute
  '/app/assessments/$id/post-test': typeof AppAssessmentsIdPostTestRoute
  '/app/assessments/$id/results': typeof AppAssessmentsIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/ai-insights'
    | '/app/ai-models'
    | '/app/ai-review'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/my-assessments'
    | '/app/my-results'
    | '/app/results'
    | '/app/system-analytics'
    | '/app/trends'
    | '/app/users'
    | '/app/'
    | '/app/assessments/$id'
    | '/app/assessments/new'
    | '/app/participants/$userId'
    | '/app/questions/$id'
    | '/app/questions/equivalent-groups'
    | '/app/trainings/$id'
    | '/assessment/$id/access'
    | '/assessment/$id/result'
    | '/assessment/$id/solve'
    | '/app/assessments/'
    | '/app/participants/'
    | '/app/questions/'
    | '/app/trainings/'
    | '/app/assessments/$id/post-test'
    | '/app/assessments/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/ai-insights'
    | '/app/ai-models'
    | '/app/ai-review'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/my-assessments'
    | '/app/my-results'
    | '/app/results'
    | '/app/system-analytics'
    | '/app/trends'
    | '/app/users'
    | '/app'
    | '/app/assessments/$id'
    | '/app/assessments/new'
    | '/app/participants/$userId'
    | '/app/questions/$id'
    | '/app/questions/equivalent-groups'
    | '/app/trainings/$id'
    | '/assessment/$id/access'
    | '/assessment/$id/result'
    | '/assessment/$id/solve'
    | '/app/assessments'
    | '/app/participants'
    | '/app/questions'
    | '/app/trainings'
    | '/app/assessments/$id/post-test'
    | '/app/assessments/$id/results'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/ai-insights'
    | '/app/ai-models'
    | '/app/ai-review'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/my-assessments'
    | '/app/my-results'
    | '/app/results'
    | '/app/system-analytics'
    | '/app/trends'
    | '/app/users'
    | '/app/'
    | '/app/assessments/$id'
    | '/app/assessments/new'
    | '/app/participants/$userId'
    | '/app/questions/$id'
    | '/app/questions/equivalent-groups'
    | '/app/trainings/$id'
    | '/assessment/$id/access'
    | '/assessment/$id/result'
    | '/assessment/$id/solve'
    | '/app/assessments/'
    | '/app/participants/'
    | '/app/questions/'
    | '/app/trainings/'
    | '/app/assessments/$id/post-test'
    | '/app/assessments/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AssessmentIdAccessRoute: typeof AssessmentIdAccessRoute
  AssessmentIdResultRoute: typeof AssessmentIdResultRoute
  AssessmentIdSolveRoute: typeof AssessmentIdSolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system-analytics': {
      id: '/app/system-analytics'
      path: '/system-analytics'
      fullPath: '/app/system-analytics'
      preLoaderRoute: typeof AppSystemAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-results': {
      id: '/app/my-results'
      path: '/my-results'
      fullPath: '/app/my-results'
      preLoaderRoute: typeof AppMyResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-assessments': {
      id: '/app/my-assessments'
      path: '/my-assessments'
      fullPath: '/app/my-assessments'
      preLoaderRoute: typeof AppMyAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-review': {
      id: '/app/ai-review'
      path: '/ai-review'
      fullPath: '/app/ai-review'
      preLoaderRoute: typeof AppAiReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-models': {
      id: '/app/ai-models'
      path: '/ai-models'
      fullPath: '/app/ai-models'
      preLoaderRoute: typeof AppAiModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-insights': {
      id: '/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trainings/': {
      id: '/app/trainings/'
      path: '/trainings'
      fullPath: '/app/trainings/'
      preLoaderRoute: typeof AppTrainingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions/': {
      id: '/app/questions/'
      path: '/questions'
      fullPath: '/app/questions/'
      preLoaderRoute: typeof AppQuestionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/participants/': {
      id: '/app/participants/'
      path: '/participants'
      fullPath: '/app/participants/'
      preLoaderRoute: typeof AppParticipantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments/': {
      id: '/app/assessments/'
      path: '/assessments'
      fullPath: '/app/assessments/'
      preLoaderRoute: typeof AppAssessmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/assessment/$id/solve': {
      id: '/assessment/$id/solve'
      path: '/assessment/$id/solve'
      fullPath: '/assessment/$id/solve'
      preLoaderRoute: typeof AssessmentIdSolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/result': {
      id: '/assessment/$id/result'
      path: '/assessment/$id/result'
      fullPath: '/assessment/$id/result'
      preLoaderRoute: typeof AssessmentIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/access': {
      id: '/assessment/$id/access'
      path: '/assessment/$id/access'
      fullPath: '/assessment/$id/access'
      preLoaderRoute: typeof AssessmentIdAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trainings/$id': {
      id: '/app/trainings/$id'
      path: '/trainings/$id'
      fullPath: '/app/trainings/$id'
      preLoaderRoute: typeof AppTrainingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions/equivalent-groups': {
      id: '/app/questions/equivalent-groups'
      path: '/questions/equivalent-groups'
      fullPath: '/app/questions/equivalent-groups'
      preLoaderRoute: typeof AppQuestionsEquivalentGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions/$id': {
      id: '/app/questions/$id'
      path: '/questions/$id'
      fullPath: '/app/questions/$id'
      preLoaderRoute: typeof AppQuestionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/participants/$userId': {
      id: '/app/participants/$userId'
      path: '/participants/$userId'
      fullPath: '/app/participants/$userId'
      preLoaderRoute: typeof AppParticipantsUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments/new': {
      id: '/app/assessments/new'
      path: '/assessments/new'
      fullPath: '/app/assessments/new'
      preLoaderRoute: typeof AppAssessmentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments/$id': {
      id: '/app/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/app/assessments/$id'
      preLoaderRoute: typeof AppAssessmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments/$id/results': {
      id: '/app/assessments/$id/results'
      path: '/results'
      fullPath: '/app/assessments/$id/results'
      preLoaderRoute: typeof AppAssessmentsIdResultsRouteImport
      parentRoute: typeof AppAssessmentsIdRoute
    }
    '/app/assessments/$id/post-test': {
      id: '/app/assessments/$id/post-test'
      path: '/post-test'
      fullPath: '/app/assessments/$id/post-test'
      preLoaderRoute: typeof AppAssessmentsIdPostTestRouteImport
      parentRoute: typeof AppAssessmentsIdRoute
    }
  }
}

interface AppAssessmentsIdRouteChildren {
  AppAssessmentsIdPostTestRoute: typeof AppAssessmentsIdPostTestRoute
  AppAssessmentsIdResultsRoute: typeof AppAssessmentsIdResultsRoute
}

const AppAssessmentsIdRouteChildren: AppAssessmentsIdRouteChildren = {
  AppAssessmentsIdPostTestRoute: AppAssessmentsIdPostTestRoute,
  AppAssessmentsIdResultsRoute: AppAssessmentsIdResultsRoute,
}

const AppAssessmentsIdRouteWithChildren =
  AppAssessmentsIdRoute._addFileChildren(AppAssessmentsIdRouteChildren)

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAiModelsRoute: typeof AppAiModelsRoute
  AppAiReviewRoute: typeof AppAiReviewRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMyAssessmentsRoute: typeof AppMyAssessmentsRoute
  AppMyResultsRoute: typeof AppMyResultsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSystemAnalyticsRoute: typeof AppSystemAnalyticsRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssessmentsIdRoute: typeof AppAssessmentsIdRouteWithChildren
  AppAssessmentsNewRoute: typeof AppAssessmentsNewRoute
  AppParticipantsUserIdRoute: typeof AppParticipantsUserIdRoute
  AppQuestionsIdRoute: typeof AppQuestionsIdRoute
  AppQuestionsEquivalentGroupsRoute: typeof AppQuestionsEquivalentGroupsRoute
  AppTrainingsIdRoute: typeof AppTrainingsIdRoute
  AppAssessmentsIndexRoute: typeof AppAssessmentsIndexRoute
  AppParticipantsIndexRoute: typeof AppParticipantsIndexRoute
  AppQuestionsIndexRoute: typeof AppQuestionsIndexRoute
  AppTrainingsIndexRoute: typeof AppTrainingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAiModelsRoute: AppAiModelsRoute,
  AppAiReviewRoute: AppAiReviewRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMyAssessmentsRoute: AppMyAssessmentsRoute,
  AppMyResultsRoute: AppMyResultsRoute,
  AppResultsRoute: AppResultsRoute,
  AppSystemAnalyticsRoute: AppSystemAnalyticsRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssessmentsIdRoute: AppAssessmentsIdRouteWithChildren,
  AppAssessmentsNewRoute: AppAssessmentsNewRoute,
  AppParticipantsUserIdRoute: AppParticipantsUserIdRoute,
  AppQuestionsIdRoute: AppQuestionsIdRoute,
  AppQuestionsEquivalentGroupsRoute: AppQuestionsEquivalentGroupsRoute,
  AppTrainingsIdRoute: AppTrainingsIdRoute,
  AppAssessmentsIndexRoute: AppAssessmentsIndexRoute,
  AppParticipantsIndexRoute: AppParticipantsIndexRoute,
  AppQuestionsIndexRoute: AppQuestionsIndexRoute,
  AppTrainingsIndexRoute: AppTrainingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AssessmentIdAccessRoute: AssessmentIdAccessRoute,
  AssessmentIdResultRoute: AssessmentIdResultRoute,
  AssessmentIdSolveRoute: AssessmentIdSolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
