sonar.projectKey=Pro-jaekt-3_Projekt3
sonar.organization=projekt3

sonar.sources=frontend-next/src,backend
sonar.exclusions=**/node_modules/**,**/migrations/**,**/seed*.js,**/*.test.*,**/__tests__/**,**/routeTree.gen.*
sonar.sourceEncoding=UTF-8